### ISSUE TITLE
Resizing the page moves the drag-and-drop object

### ISSUE THREAD

**Issue by zzirGio** [emgoto/new-horizons#1]
Steps to reproduce:
1. Drag and drop the object onto the map
2. Resize the page.
3. Notice that the object has moved relative to its position on the map.

Expected behavior:
The drag-and-drop object should stick to its position on the map.

Actual behavior:
The drag-and-drop object moves relative to its position on the map.

**Comment by emgoto** [comment]
Interestingly I would say it's actually the canvas resizing that is causing these issues. I have fixed this problem in my latest commit.
